/*********************************
//form analytics test script - speudo code to validate concept KPI's
//test on https://www.centraalbeheer.nl/verzekeringen/woonverzekering/premie-berekenen/Paginas/Stap-1.aspx


//steps to include the script easily to your console

$.getScript( "https://www.centraalbeheer.dev/relay42/form/formanalytics.js", function( data, textStatus, jqxhr ) {
  console.log( data ); // Data returned
  console.log( textStatus ); // Success
  console.log( jqxhr.status ); // 200
  console.log( "Load was performed." );
});

*********************************/



/*********************************
	FORM STEP COMPLETION TIME
*********************************/

//create vars
var form_step_completion_start = null;
var form_step_completion_end = null;
var form_step_completion_time = null;

//register form start
$("input").on('focus', function(){
	
	if(form_step_completion_start === null){
		form_step_completion_start = new Date().getTime()
		console.log("form_step_completion_start: " + form_step_completion_start);
	}

});

//register form end
$("form").on('submit', function(){
	// submit POST methode will not always be used, could also be a simple button with Angular. 
	// if the next button does display a new step but doesn't trigger a submit, 
	// that button should also be used to trigger form_step_completion time
	
	if(form_step_completion_end === null){
		form_step_completion_end = new Date().getTime()
	}
		
	console.log("form_step_completion_end: " + form_step_completion_start);
	
	//detract timestamps and create readable time in seconds
	form_step_completion_time = (form_step_completion_end - form_step_completion_start) / 1000;
	
	//send an event to Google Analytics with completion time
	//arguably best to send it as a custom metric along with the button click event 
	//if the button succesfully triggers the next page
	console.log("form_step_completion_time (in seconds): " + form_step_completion_time);
});


/*********************************
	ZWAKKE VELDEN
*********************************/

//register enter fields
$("input").on('focus', function(){
	
	//create vars
	var form_field_completion_start = null;
	var form_field_completion_end = null;
	var form_field_completion_time = null;	
	
	if(form_step_completion_start === null){
		form_field_completion_start = new Date().getTime()
		console.log("form_field_completion_start: " + form_field_completion_start);
	}

	//clean up the name attributed if uniquely generated by sharepoint formcontrols
	var name = $(this).attr('name');
	if( name.match("^ctl") ){
		name = name.substring(name.lastIndexOf('_'));
		if(name.match("^_")){
			name = name.substring(1);	
		}
	}
	
	$(this).on('blur', function(){

		if(form_field_completion_end === null){
			form_field_completion_end = new Date().getTime();
		}
			
		console.log("form_field_completion_end: " + form_field_completion_start);
		
		//detract timestamps and create readable time in seconds
		form_field_completion_time = (form_field_completion_end - form_field_completion_start) / 1000;
		
		//send an event to Google Analytics with completion time
		console.log("field " + name + " completed in: " + form_field_completion_time + "s");
		
		
	});	
	
});

/* research input */

/*
	
	// document.activeElement // body of undefined is geen active element, anders wel
	// body? -> document.activeElement === document.body
	// a? === element.tagName === 'A' || 'a'

// input not touched

<input name="ctl00$m$g_638f0cdf_f0a1_4fbc_aba7_c75ab972a0e3$ctl01$_postcodeRisicoAdres" type="text" id="ctl00_m_g_638f0cdf_f0a1_4fbc_aba7_c75ab972a0e3_ctl01__postcodeRisicoAdres" maxlength="7" class="input-mini" data-validation="{required:true, cvZipCode:true}" data-bind="value: postcode" onchange="this.value = formatPostcode(this.value); toggleAdresOpgehaald('')" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAjZJREFUWAntV7vKIlEMPt5dOy/NID9WIoKKCAsiWIqFFmLra4j2IoKPsL24YKWFD7Ai+ASClY2yNioWgjckfzLrCeN46XSKNXDmJPkyyWdOZnCE+CdfuP3G9RcXvHhRDapFNVUhZYXr1YX1+anmlwUvv3D9xPVu+YEFFRNeqCXKu6tf6i2IALXGMDEbVvlS+EPg/+tAuVwWmUyGR+/tHSgUCiKdThtHgCs/egosFouIRCIiEAjoY9n2+XwikUgIp9PJPq1itVpFLBYTfr9f636o8zs6GAzCeDwGKb1eD1wuF+OYARqNBpzPZzVkuVxCNpu9wuPxOEynU5kCWq0W2Gw2jhkOh1Cr1dgmVmyMRiO+USrNZpNxPD/p5n29XoPb7VZjTCYTTCYTxqRSqVQ4h54AD6HX6xXJZPKmTblcjn35fJ51qWBxkUqlVBM7KEKhkIR41+Zg50VhAofDQSBjPS72+z37tDo7Udntdqopdy1G+qP7CGMC2+1WdLtd8l0JniHb7Xb7hiSet8CjU2Nms5kYDAYcLxVtDunT7nw+Ho8HOp0OYDdgs9lAvV4Hs9nMON4EpVIJ5vO5Oog0M+Fw+ApXFAX6/T4cj0dYrVZQrVavcP0MEJGrALJpammg7mHS53A4nuJ2u/0uridgxYQ3cjqdbnx6B83MM8EOPIMZ4xlgjwHK3VYhj5f4i8UiRKNRzv35S2b4DHwIUAcWBjx5suSCCPyRlgG7WtvQj1P5o4kEfTK//fP8G/4x2UymA12DAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">

//input touched

<input name="ctl00$m$g_638f0cdf_f0a1_4fbc_aba7_c75ab972a0e3$ctl01$_postcodeRisicoAdres" type="text" id="ctl00_m_g_638f0cdf_f0a1_4fbc_aba7_c75ab972a0e3_ctl01__postcodeRisicoAdres" maxlength="7" class="input-mini" data-validation="{required:true, cvZipCode:true}" data-bind="value: postcode" onchange="this.value = formatPostcode(this.value); toggleAdresOpgehaald('')" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAmJJREFUWAntV7uKIkEUvbYGM4KID3wEIgjKRLLpKGLgFwiCfslGhkb7IbLgAzE1GhMxWxRRBEEwmEgDERWfW6fXuttq60a2wU6B1qlzb9U5fatsKROJVigUArvd7oeAyePx6Af3qGYymT7F2h8Wi+V7Pp+fmE7iv4Sw81GieusKIzNh4puCJzdaHIagCW1F4KSeQ4O4pPLoPb/3INBGBZ7avgz8fxWIxWIUCoX43Blegbe3NwoGg88zwMoncFUB8Yokj8dDdrv9MpfHVquV/H4/iVcpc1qgKAp5vV6y2WxaWhefreB0OimXy6kGkD0YDKhSqdB2u+XJqVSK4vE4QWS5XKrx0WjEcZ/PR9lslhwOh8p1Oh2q1Wp0OBw4RwvOKpBOp1kcSdivZPLvmxrjRCKhiiOOSmQyGXp5ecFQbRhLcRDRaJTe39//BHW+2cDr6ysFAoGrlEgkwpwWS1I7z+VykdvtliHuw+Ew40vABvb7Pf6hLuMk/rGY02ImBZC8dqv04lpOYjaw2WzUPZcB2WMPZet2u1cmZ7MZTSYTNWU+n9N4PJbp3GvXYPIE2ADG9Xqder2e+kTr9ZqazSa1222eA6FqtUoQwqHCuFgscgWQWC6XaTgcEiqKQ9poNOiegbNfwWq1olKppB6yW6cWVcDHbDarIuzuBBaLhWrqVvwy/6wCMnhLXMbR4wnvtX/F5VxdAzJoRH+2BUYItlotmk6nLGW4gX6/z+IAT9+CLwPPr8DprnZ2MIwaQBsV+DBKUEfnQ8EtFRdFneBDKWhCW8EVGbdUQfxESR6qKhaHBrSgCe3fbLTpPlS70M0AAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">

//input filled in not correct

<input name="ctl00$m$g_638f0cdf_f0a1_4fbc_aba7_c75ab972a0e3$ctl01$_postcodeRisicoAdres" type="text" id="ctl00_m_g_638f0cdf_f0a1_4fbc_aba7_c75ab972a0e3_ctl01__postcodeRisicoAdres" maxlength="7" class="input-mini" data-validation="{required:true, cvZipCode:true}" data-bind="value: postcode" onchange="this.value = formatPostcode(this.value); toggleAdresOpgehaald('')" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAmJJREFUWAntV7uKIkEUvbYGM4KID3wEIgjKRLLpKGLgFwiCfslGhkb7IbLgAzE1GhMxWxRRBEEwmEgDERWfW6fXuttq60a2wU6B1qlzb9U5fatsKROJVigUArvd7oeAyePx6Af3qGYymT7F2h8Wi+V7Pp+fmE7iv4Sw81GieusKIzNh4puCJzdaHIagCW1F4KSeQ4O4pPLoPb/3INBGBZ7avgz8fxWIxWIUCoX43Blegbe3NwoGg88zwMoncFUB8Yokj8dDdrv9MpfHVquV/H4/iVcpc1qgKAp5vV6y2WxaWhefreB0OimXy6kGkD0YDKhSqdB2u+XJqVSK4vE4QWS5XKrx0WjEcZ/PR9lslhwOh8p1Oh2q1Wp0OBw4RwvOKpBOp1kcSdivZPLvmxrjRCKhiiOOSmQyGXp5ecFQbRhLcRDRaJTe39//BHW+2cDr6ysFAoGrlEgkwpwWS1I7z+VykdvtliHuw+Ew40vABvb7Pf6hLuMk/rGY02ImBZC8dqv04lpOYjaw2WzUPZcB2WMPZet2u1cmZ7MZTSYTNWU+n9N4PJbp3GvXYPIE2ADG9Xqder2e+kTr9ZqazSa1222eA6FqtUoQwqHCuFgscgWQWC6XaTgcEiqKQ9poNOiegbNfwWq1olKppB6yW6cWVcDHbDarIuzuBBaLhWrqVvwy/6wCMnhLXMbR4wnvtX/F5VxdAzJoRH+2BUYItlotmk6nLGW4gX6/z+IAT9+CLwPPr8DprnZ2MIwaQBsV+DBKUEfnQ8EtFRdFneBDKWhCW8EVGbdUQfxESR6qKhaHBrSgCe3fbLTpPlS70M0AAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">

//input filled in and valid

<input name="ctl00$m$g_638f0cdf_f0a1_4fbc_aba7_c75ab972a0e3$ctl01$_postcodeRisicoAdres" type="text" id="ctl00_m_g_638f0cdf_f0a1_4fbc_aba7_c75ab972a0e3_ctl01__postcodeRisicoAdres" maxlength="7" class="input-mini valid" data-validation="{required:true, cvZipCode:true}" data-bind="value: postcode" onchange="this.value = formatPostcode(this.value); toggleAdresOpgehaald('')" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAmJJREFUWAntV7uKIkEUvbYGM4KID3wEIgjKRLLpKGLgFwiCfslGhkb7IbLgAzE1GhMxWxRRBEEwmEgDERWfW6fXuttq60a2wU6B1qlzb9U5fatsKROJVigUArvd7oeAyePx6Af3qGYymT7F2h8Wi+V7Pp+fmE7iv4Sw81GieusKIzNh4puCJzdaHIagCW1F4KSeQ4O4pPLoPb/3INBGBZ7avgz8fxWIxWIUCoX43Blegbe3NwoGg88zwMoncFUB8Yokj8dDdrv9MpfHVquV/H4/iVcpc1qgKAp5vV6y2WxaWhefreB0OimXy6kGkD0YDKhSqdB2u+XJqVSK4vE4QWS5XKrx0WjEcZ/PR9lslhwOh8p1Oh2q1Wp0OBw4RwvOKpBOp1kcSdivZPLvmxrjRCKhiiOOSmQyGXp5ecFQbRhLcRDRaJTe39//BHW+2cDr6ysFAoGrlEgkwpwWS1I7z+VykdvtliHuw+Ew40vABvb7Pf6hLuMk/rGY02ImBZC8dqv04lpOYjaw2WzUPZcB2WMPZet2u1cmZ7MZTSYTNWU+n9N4PJbp3GvXYPIE2ADG9Xqder2e+kTr9ZqazSa1222eA6FqtUoQwqHCuFgscgWQWC6XaTgcEiqKQ9poNOiegbNfwWq1olKppB6yW6cWVcDHbDarIuzuBBaLhWrqVvwy/6wCMnhLXMbR4wnvtX/F5VxdAzJoRH+2BUYItlotmk6nLGW4gX6/z+IAT9+CLwPPr8DprnZ2MIwaQBsV+DBKUEfnQ8EtFRdFneBDKWhCW8EVGbdUQfxESR6qKhaHBrSgCe3fbLTpPlS70M0AAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: pointer;">

*/

